// This file is generated by Scripts/generate_typed_cli_action_catalog.swift.
// Edit Scripts/AutomationCLIActionCatalog.json, then regenerate this file.

extension AutomationCLIActionCatalog {
    static let all: [AutomationCLIAction] = [
        entry(AccountsListCommand.self),
        entry(AccountsAddCommand.self),
        entry(AccountsRemoveCommand.self),
        entry(AccountsVerifyCommand.self),
        entry(AppsListCommand.self),
        entry(AppsGetCommand.self),
        entry(AppVersionListCommand.self),
        entry(AppVersionGetCommand.self),
        entry(BuildsListCommand.self),
        entry(AppVersionCreateCommand.self),
        entry(ReviewsListCommand.self),
        entry(ReviewsGetCommand.self)
    ]

    static let generatedActionIDs: [String] = [
        "list_accounts",
        "add_account",
        "remove_account",
        "verify_account",
        "list_apps",
        "get_app",
        "list_app_versions",
        "get_app_version",
        "list_builds",
        "create_app_version",
        "list_customer_reviews",
        "get_customer_review"
    ]
}