import Foundation

struct Entry: Decodable {
    let id: String
    let commandType: String
}

let root = URL(fileURLWithPath: #filePath).deletingLastPathComponent().deletingLastPathComponent()
let input = root.appending(path: "Scripts/AutomationCLIActionCatalog.json")
let output = root.appending(path: "Sources/AppDabCLIKit/Commands/AutomationCLIActionCatalog+Generated.swift")
let entries = try JSONDecoder().decode([Entry].self, from: Data(contentsOf: input))

let body = """
// This file is generated by Scripts/generate_typed_cli_action_catalog.swift.
// Edit Scripts/AutomationCLIActionCatalog.json, then regenerate this file.

extension AutomationCLIActionCatalog {
    static let all: [AutomationCLIAction] = [
\(entries.map { "        entry(\($0.commandType).self)" }.joined(separator: ",\n"))
    ]

    static let generatedActionIDs: [String] = [
\(entries.map { "        \"\($0.id)\"" }.joined(separator: ",\n"))
    ]
}
"""

if CommandLine.arguments.contains("--check") {
    guard (try? String(contentsOf: output, encoding: .utf8)) == body else {
        fputs("Generated CLI action catalog is out of date. Run swift Scripts/generate_typed_cli_action_catalog.swift.\n", stderr)
        exit(1)
    }
} else {
    try body.write(to: output, atomically: true, encoding: .utf8)
}
